apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-certificate
spec:
  dnsNames:
    - janus-idp.operate-first.cloud
  issuerRef:
    name: letsencrypt
  secretName: janus-idp-cert
