apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: janus-idp
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: moc/smaug/janus-idp/values-app-config
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: opf-vault-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: janus-idp
