apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: https://janus-idp.io
    - title: Blog
      url: https://janus-idp.io/blog
    - title: Slack
      url: https://join.slack.com/t/janus-idp/shared_invite/zt-1nii16o6e-SGscZ4YtAktL6rRtZZBUfA
  annotations:
    github.com/project-slug: janus-idp/backstage-showcase
spec:
  type: library
  owner: janus-authors
  lifecycle: experimental