apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-showcase
  description: |
    This is the Janus Community Showcase of Backstage.io
  links:
    - title: Website
      url: https://janus-idp.io
    - title: Blog
      url: https://janus-idp.io/blog
    - title: Slack
      url: https://join.slack.com/t/janus-idp/shared_invite/zt-1nii16o6e-SGscZ4YtAktL6rRtZZBUfA
  annotations:
    argocd/app-name: "janus-idp-smaug"
    backstage.io/kubernetes-id: "janus-idp"
    github.com/project-slug: janus-idp/backstage-showcase
    quay.io/repository-slug: janus-idp/backstage-showcase
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: janus-idp
spec:
  type: website
  owner: janus-authors
  lifecycle: production
